Traducción en francés
Añadí la función set_ui_fr
Cambié la parte donde se configura la selección del idioma

Bug que no pude resolverlo: a la línea que muestra dueño, grupo y
sistema le falta 2 espacios en la parte sistema para que la barra vertical esté alineada con
las líneas siguientes. Es decir:

Propriétaire:   yp  | Groupe:      yp  | Autres        |
Lecture:       oui  | Lecture:    oui  | Lecture:    oui  |
Écriture:      oui  | Écriture:   non  | Écriture:   non  |
Exécution:     oui  | Exécution:  oui  | Exécution:  oui  |

diff --git a/src/detail b/src/detail
--- a/src/detail
+++ b/src/detail
@@ -53,19 +53,43 @@ echo 'ui_file="Archivo"
 ' > ~/.detail.conf
 }
 
+function set_ui_fr() {
+echo 'ui_file="Fichier"
+    ui_dir="Répertoire"
+    ui_link="Lien"
+    ui_name="Nom"
+    ui_type="Type"
+    ui_owner="Propriétaire"
+    ui_group="Groupe"
+    ui_system="Autres"
+    ui_perm_r="Lecture"
+    ui_perm_w="Écriture"
+    ui_perm_x="Exécution"
+    ui_perm_yes="oui"
+    ui_perm_no="non"
+    error_msg="Nom de Répertoire, Lien ou Fichier incorrect"
+    error_msg2="Usage: detail (ou det) <fichier/lien/répertoire>"
+    error_msg3="Veuillez réessayer"
+' > ~/.detail.conf
+}
+
 if [[ ! -e ~/.detail.conf ]]; then
 clear
     echo "[English] It seems like this is your first time running Detail $version"
-    echo "Would you like this software to run in English or Spanish?"
+    echo "Would you like this software to run in English, Spanish or French?"
     echo ""
     echo "[Español] Parece que estás utilizando detail $version por primera vez"
     echo "Necesitás configurar el idioma para continuar"
     echo ""
+    echo "[Français] Il semble que vous utilisez detail $version pour la première fois"
+    echo "Quelle langue voulez-vous utiliser?"
+    echo ""
 	echo "Available Languages"
 	echo "1: English"
 	echo "2: Español"
+        echo "3: Français"
 	echo ""
-	echo -ne "Selection: [1/2]:" 
+	echo -ne "Selection: [1/2/3]:" 
     	read -r x
     	case $x in
 		 1)
@@ -80,8 +104,14 @@ clear
  		echo "Por favor ejecute detail nuevamente"
            	exit 1
 		;;
+                3)
+		set_ui_fr
+	        echo "Langue Sélectionnée: Français"
+ 		echo "Veuillez relancer detail"
+           	exit 1
+		;;
         	*)
-            	echo "Error: Options are 1 or 2"
+            	echo "Error: Options are 1, 2 or 3"
             	exit 1
             	;;
     esac
